services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${TRACKS_DB:-tracks}
  web:
    build:
      context: ..
      target: test
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    environment:
      # These are set in script/cibuild, so we need to pass-thru them.
      RAILS_ENV: $RAILS_ENV
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USERNAME: root
      DATABASE_PASSWORD_EMPTY: 1
    volumes:
      - ${VOLUME:-..}/config/database.docker.yml:/app/config/database.yml:Z
      - ${VOLUME:-..}/config/site.docker.yml:/app/config/site.yml:Z
    ports:
      - 3000:3000
    depends_on:
      - db
