services:
  web:
    build:
      context: ..
      target: test
      args:
        RUBY_VERSION: ${RUBY_VERSION}
    environment:
      # These are set in script/cibuild, so we need to pass-thru them.
      RAILS_ENV: $RAILS_ENV
      DATABASE_NAME: "/app/db/db.sqlite"
      DATABASE_TYPE: sqlite3
    volumes:
      - sqlite:/app/db:Z
      - ${VOLUME:-..}/config/database.docker.yml:/app/config/database.yml:Z
      - ${VOLUME:-..}/config/site.docker.yml:/app/config/site.yml:Z
    ports:
      - 3000:3000
volumes:
  sqlite: {}
