test:
  adapter: <%= ENV.fetch('DATABASE_TYPE') %>
  encoding: <%= ENV.fetch('DATABASE_ENCODING') %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

development:
  adapter: <%= ENV.fetch('DATABASE_TYPE') %>
  encoding: <%= ENV.fetch('DATABASE_ENCODING') %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>

production:
  adapter: <%= ENV.fetch('DATABASE_TYPE') %>
  encoding: <%= ENV.fetch('DATABASE_ENCODING') %>
  database: <%= ENV.fetch('DATABASE_NAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
