---
name: 'Build custom release'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string
      name:
        description: 'Name of the release'
        required: true
        type: string

jobs:
  build-and-publish-release:
    name: 'Build custom release'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          target: production
          push: true
          tags: |
            tracksapp/tracks:${{ inputs.name }}
            ghcr.io/tracksapp/tracks:${{ inputs.name }}

#          platforms: linux/amd64,linux/arm64
